services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql